# Generated by Django 2.2.6 on 2019-10-23 13:31

import core.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_phone', models.CharField(max_length=32, validators=[core.validators.MobilePhoneValidator()])),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('home', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_phone', models.CharField(max_length=32, validators=[core.validators.MobilePhoneValidator()])),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('home_area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('dest_range', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('actual_route', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('distance', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('CREATED BY CLIENT', 'CREATED BY CLIENT'), ('CONFIRMED BY CLIENT', 'CONFIRMED BY CLIENT'), ('VISIBLE FOR DRIVERS', 'VISIBLE FOR DRIVERS'), ('ACCEPTED BY DRIVER', 'ACCEPTED BY DRIVER'), ('DRIVER IS COMING', 'DRIVER IS COMING'), ('DRIVER IS WAITING', 'DRIVER IS WAITING'), ('RIDING', 'RIDING'), ('FINISHED', 'FINISHED')], default='CREATED BY CLIENT', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='core.Client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='core.Driver')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
    ]
