# Generated by Django 2.2.6 on 2019-10-25 09:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_phone',
            field=models.CharField(max_length=32, unique=True, validators=[core.validators.MobilePhoneValidator()]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobile_phone',
            field=models.CharField(max_length=32, unique=True, validators=[core.validators.MobilePhoneValidator()]),
        ),
    ]
